# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['run_server.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('templates', 'templates'),
        ('static', 'static'),
    ],
    hiddenimports=[
        'django',
        'django.core.management',
        'django.core.wsgi',
        'django.conf',
        'django.db',
        'django.contrib',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.auth',
        'django.contrib.staticfiles',
        'rest_framework',
        'django_filters',
        'widget_tweaks',
        ' Attendance',
        'VIPAlert',
        'HTI',
        'waitress',
        'xlsxwriter',
        'xlrd',
        'pyzk',
        'pytz',
        'arabic_reshaper',
        'python_bidi',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='run_server',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)