# Generated by Django 4.2.24 on 2026-04-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("VIPAlert", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_admin",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user has admin privileges.",
                verbose_name="admin status",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can log into this admin site.",
                verbose_name="staff status",
            ),
        ),
    ]
