# Generated by Django 4.2.24 on 2026-04-29 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("VIPAlert", "0002_user_is_active_alter_user_is_admin_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("can_view_users", "عرض المستخدمين"),
                    ("can_create_users", "إضافة مستخدمين"),
                    ("can_edit_users", "تعديل المستخدمين"),
                    ("can_delete_users", "حذف المستخدمين"),
                    ("can_change_users_passwords", "تغيير كلمات مرور المستخدمين"),
                    ("can_view_logs", "عرض سجلات النظام"),
                    ("can_manage_attendance", "إدارة الحضور والانصراف"),
                    ("can_manage_employees", "إدارة الموظفين"),
                    ("can_manage_vacations", "إدارة الإجازات والأذونات"),
                    ("can_manage_devices", "إدارة الأجهزة"),
                    ("can_manage_settings", "إدارة إعدادات النظام"),
                    ("can_view_reports", "عرض التقارير"),
                ]
            },
        ),
        migrations.CreateModel(
            name="SystemLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("INFO", "معلومات"),
                            ("WARNING", "تحذير"),
                            ("ERROR", "خطأ"),
                            ("CRITICAL", "حرج"),
                        ],
                        default="INFO",
                        max_length=10,
                    ),
                ),
                ("action", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("path", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
