import sys

with open('/Users/zakaria/projects/antigravity/attendance/Attendance/views.py', 'r') as f:
    lines = f.readlines()

new_lines = []
skip_until = None

# Identify sections to keep and sections to rewrite
# We'll keep everything until VacationsView (line 682)
# and everything from AddPermission (line 982)

for i, line in enumerate(lines):
    line_num = i + 1
    
    if skip_until and line_num < skip_until:
        continue
    if skip_until and line_num == skip_until:
        skip_until = None
        continue

    if "class VacationsView(ListView):" in line:
        # Start of the messy section
        new_lines.append("\n\nclass VacationsView(ListView):\n")
        new_lines.append("    template_name = \"attendance/vacations/vacations_list_view.html\"\n")
        new_lines.append("    form_class = Vacation\n")
        new_lines.append("    model = Vacation\n\n")
        new_lines.append("    def get_context_data(self, **kwargs):\n")
        new_lines.append("        data = super().get_context_data(**kwargs)\n")
        new_lines.append("        data[\"search_form\"] = FilterVacationsForm()\n")
        new_lines.append("        return data\n\n")
        new_lines.append("    def get_queryset(self):\n")
        new_lines.append("        q = super().get_queryset()\n")
        new_lines.append("        g = self.request.GET\n")
        new_lines.append("        if g.get('employees', \"\") != \"\":\n")
        new_lines.append("            q = q.filter(employee_id=g.get('employees', None))\n")
        new_lines.append("        if g.get('vacation_type', \"\") != \"\":\n")
        new_lines.append("            q = q.filter(vacation_type_id=g.get('vacation_type', None))\n")
        new_lines.append("        if g.get('date', \"\") != \"\":\n")
        new_lines.append("            q = q.filter(date__gte=g.get('date', None))\n")
        new_lines.append("        if g.get('to_date', \"\") != \"\":\n")
        new_lines.append("            q = q.filter(date__lte=g.get('to_date', None))\n")
        new_lines.append("        return q\n\n")
        new_lines.append("    def get(self, request, *args, **kwargs):\n")
        new_lines.append("        return super().get(request, *args, **kwargs)\n\n\n")
        
        new_lines.append("class AddVacationsView(PermissionRequiredMixin, FormView):\n")
        new_lines.append("    template_name = \"attendance/vacations/add_edit_vacation.html\"\n")
        new_lines.append("    form_class = AddVacationForm\n")
        new_lines.append("    model = Vacation\n")
        new_lines.append("    success_url = reverse_lazy(\"Attendance:vacation\")\n")
        new_lines.append("    permission_required = ('Attendance.can_create_employees',)\n")
        new_lines.append("    raise_exception = True\n\n")
        new_lines.append("    def form_valid(self, form):\n")
        new_lines.append("        date = form.cleaned_data['date']\n")
        new_lines.append("        to_date = form.cleaned_data['to_date']\n")
        new_lines.append("        vacation_type = form.cleaned_data['type']\n")
        new_lines.append("        employees = form.cleaned_data['employees']\n")
        new_lines.append("        note = form.cleaned_data['note']\n")
        new_lines.append("        for employee in employees:\n")
        new_lines.append("            v = Vacation(employee=employee, date=date, to_date=to_date, vacation_type=vacation_type, note=note)\n")
        new_lines.append("            v.save()\n")
        new_lines.append("            employee.current_vacations = employee.current_vacations - (to_date - date).days\n")
        new_lines.append("            employee.save()\n\n")
        new_lines.append("        SystemLog.objects.create(\n")
        new_lines.append("            user=self.request.user,\n")
        new_lines.append("            action=\"إضافة إجازات جماعية\",\n")
        new_lines.append("            description=f\"تم إضافة إجازة لعدد {employees.count()} موظف للفترة من {date} إلى {to_date}\",\n")
        new_lines.append("            ip_address=self.request.META.get('REMOTE_ADDR')\n")
        new_lines.append("        )\n")
        new_lines.append("        return super().form_valid(form)\n\n\n")

        new_lines.append("class EditVacationView(PermissionRequiredMixin, UpdateView):\n")
        new_lines.append("    template_name = \"attendance/vacations/edit_vacation.html\"\n")
        new_lines.append("    form_class = EditVacationForm\n")
        new_lines.append("    model = Vacation\n")
        new_lines.append("    success_url = reverse_lazy(\"Attendance:vacation\")\n")
        new_lines.append("    permission_required = ('Attendance.can_create_employees',)\n")
        new_lines.append("    raise_exception = True\n\n")
        new_lines.append("    def form_valid(self, form):\n")
        new_lines.append("        response = super().form_valid(form)\n")
        new_lines.append("        SystemLog.objects.create(\n")
        new_lines.append("            user=self.request.user,\n")
        new_lines.append("            action=\"تعديل إجازة\",\n")
        new_lines.append("            description=f\"تم تعديل إجازة الموظف: {self.object.employee.name}\",\n")
        new_lines.append("            ip_address=self.request.META.get('REMOTE_ADDR')\n")
        new_lines.append("        )\n")
        new_lines.append("        return response\n\n\n")

        new_lines.append("class DeleteVacationView(PermissionRequiredMixin, DeleteView):\n")
        new_lines.append("    permission_required = ('Attendance.can_create_employees',)\n")
        new_lines.append("    raise_exception = True\n")
        new_lines.append("    model = Vacation\n")
        new_lines.append("    success_url = reverse_lazy(\"Attendance:vacation\")\n\n")
        new_lines.append("    def delete(self, request, *args, **kwargs):\n")
        new_lines.append("        obj = self.get_object()\n")
        new_lines.append("        SystemLog.objects.create(\n")
        new_lines.append("            user=self.request.user,\n")
        new_lines.append("            action=\"حذف إجازة\",\n")
        new_lines.append("            description=f\"تم حذف إجازة الموظف: {obj.employee.name} للفترة من {obj.date} إلى {obj.to_date}\",\n")
        new_lines.append("            ip_address=self.request.META.get('REMOTE_ADDR')\n")
        new_lines.append("        )\n")
        new_lines.append("        return super().delete(request, *args, **kwargs)\n\n")
        new_lines.append("    def get(self, request, *args, **kwargs):\n")
        new_lines.append("        return self.delete(request, *args, **kwargs)\n\n\n")

        new_lines.append("class AddVacationTypeView(PermissionRequiredMixin, CreateView):\n")
        new_lines.append("    permission_required = ('Attendance.can_create_employees',)\n")
        new_lines.append("    raise_exception = True\n")
        new_lines.append("    template_name = \"attendance/vacations/add_edit_vacation_type.html\"\n")
        new_lines.append("    form_class = AddVacationTypeForm\n")
        new_lines.append("    model = VacationType\n")
        new_lines.append("    success_url = reverse_lazy(\"Attendance:vacation_types\")\n\n")
        new_lines.append("    def form_valid(self, form):\n")
        new_lines.append("        response = super().form_valid(form)\n")
        new_lines.append("        SystemLog.objects.create(\n")
        new_lines.append("            user=self.request.user,\n")
        new_lines.append("            action=\"إضافة نوع إجازة\",\n")
        new_lines.append("            description=f\"تم إضافة نوع إجازة جديد: {self.object.name}\",\n")
        new_lines.append("            ip_address=self.request.META.get('REMOTE_ADDR')\n")
        new_lines.append("        )\n")
        new_lines.append("        return response\n\n\n")

        new_lines.append("class EditVacationTypeView(PermissionRequiredMixin, UpdateView):\n")
        new_lines.append("    permission_required = ('Attendance.can_create_employees',)\n")
        new_lines.append("    raise_exception = True\n")
        new_lines.append("    template_name = \"attendance/vacations/add_edit_vacation_type.html\"\n")
        new_lines.append("    form_class = AddVacationTypeForm\n")
        new_lines.append("    model = VacationType\n")
        new_lines.append("    success_url = reverse_lazy(\"Attendance:vacation_types\")\n\n")
        new_lines.append("    def form_valid(self, form):\n")
        new_lines.append("        response = super().form_valid(form)\n")
        new_lines.append("        SystemLog.objects.create(\n")
        new_lines.append("            user=self.request.user,\n")
        new_lines.append("            action=\"تعديل نوع إجازة\",\n")
        new_lines.append("            description=f\"تم تعديل نوع الإجازة: {self.object.name}\",\n")
        new_lines.append("            ip_address=self.request.META.get('REMOTE_ADDR')\n")
        new_lines.append("        )\n")
        new_lines.append("        return response\n\n\n")

        new_lines.append("class DeleteVacationTypeView(PermissionRequiredMixin, DeleteView):\n")
        new_lines.append("    permission_required = ('Attendance.can_create_employees',)\n")
        new_lines.append("    raise_exception = True\n")
        new_lines.append("    model = VacationType\n")
        new_lines.append("    success_url = reverse_lazy(\"Attendance:vacation_types\")\n\n")
        new_lines.append("    def delete(self, request, *args, **kwargs):\n")
        new_lines.append("        obj = self.get_object()\n")
        new_lines.append("        SystemLog.objects.create(\n")
        new_lines.append("            user=self.request.user,\n")
        new_lines.append("            action=\"حذف نوع إجازة\",\n")
        new_lines.append("            description=f\"تم حذف نوع الإجازة: {obj.name}\",\n")
        new_lines.append("            ip_address=self.request.META.get('REMOTE_ADDR')\n")
        new_lines.append("        )\n")
        new_lines.append("        return super().delete(request, *args, **kwargs)\n\n\n")

        new_lines.append("class ExceptionsView(ListView):\n")
        new_lines.append("    template_name = \"attendance/exceptions/exceptions_list_view.html\"\n")
        new_lines.append("    model = Exception\n\n")
        new_lines.append("    def get_queryset(self):\n")
        new_lines.append("        q = super().get_queryset()\n")
        new_lines.append("        g = self.request.GET\n")
        new_lines.append("        if g.get('employees', \"\") != \"\":\n")
        new_lines.append("            q = q.filter(employee_id=g.get('employees', None))\n")
        new_lines.append("        if g.get('type', \"\") != \"\":\n")
        new_lines.append("            q = q.filter(type=g.get('type', None))\n")
        new_lines.append("        if g.get('date', \"\") != \"\":\n")
        new_lines.append("            q = q.filter(date__gte=g.get('date', None))\n")
        new_lines.append("        return q\n\n")
        new_lines.append("    def get_context_data(self, **kwargs):\n")
        new_lines.append("        data = super().get_context_data(**kwargs)\n")
        new_lines.append("        data[\"search_form\"] = FilterExceptionsForm()\n")
        new_lines.append("        return data\n\n")
        new_lines.append("    def get(self, request, *args, **kwargs):\n")
        new_lines.append("        return super().get(request, *args, **kwargs)\n\n\n")

        new_lines.append("class AddExceptionsView(PermissionRequiredMixin, FormView):\n")
        new_lines.append("    template_name = \"attendance/exceptions/add_edit_exception.html\"\n")
        new_lines.append("    form_class = AddExceptionForm\n")
        new_lines.append("    model = Exception\n")
        new_lines.append("    success_url = reverse_lazy(\"Attendance:exception\")\n")
        new_lines.append("    permission_required = ('Attendance.can_create_employees',)\n")
        new_lines.append("    raise_exception = True\n\n")
        new_lines.append("    def form_valid(self, form):\n")
        new_lines.append("        date = form.cleaned_data['date']\n")
        new_lines.append("        exception_type = form.cleaned_data['type']\n")
        new_lines.append("        employees = form.cleaned_data['employees']\n")
        new_lines.append("        note = form.cleaned_data['note']\n")
        new_lines.append("        for employee in employees:\n")
        new_lines.append("            e = Exception(employee=employee, date=date, type=exception_type, note=note)\n")
        new_lines.append("            e.save()\n\n")
        new_lines.append("        SystemLog.objects.create(\n")
        new_lines.append("            user=self.request.user,\n")
        new_lines.append("            action=\"إضافة استثناءات جماعية\",\n")
        new_lines.append("            description=f\"تم إضافة استثناء {dict(Exception.types).get(exception_type)} لعدد {employees.count()} موظف بتاريخ {date}\",\n")
        new_lines.append("            ip_address=self.request.META.get('REMOTE_ADDR')\n")
        new_lines.append("        )\n")
        new_lines.append("        return super().form_valid(form)\n\n\n")

        new_lines.append("class DeleteExceptionView(PermissionRequiredMixin, DeleteView):\n")
        new_lines.append("    permission_required = ('Attendance.can_create_employees',)\n")
        new_lines.append("    raise_exception = True\n")
        new_lines.append("    model = Exception\n")
        new_lines.append("    success_url = reverse_lazy(\"Attendance:exception\")\n\n")
        new_lines.append("    def delete(self, request, *args, **kwargs):\n")
        new_lines.append("        obj = self.get_object()\n")
        new_lines.append("        SystemLog.objects.create(\n")
        new_lines.append("            user=self.request.user,\n")
        new_lines.append("            action=\"حذف استثناء\",\n")
        new_lines.append("            description=f\"تم حذف استثناء الموظف: {obj.employee.name} بتاريخ {obj.date}\",\n")
        new_lines.append("            ip_address=self.request.META.get('REMOTE_ADDR')\n")
        new_lines.append("        )\n")
        new_lines.append("        return super().delete(request, *args, **kwargs)\n\n\n")

        new_lines.append("class EditExceptionView(PermissionRequiredMixin, UpdateView):\n")
        new_lines.append("    permission_required = ('Attendance.can_create_employees',)\n")
        new_lines.append("    raise_exception = True\n")
        new_lines.append("    template_name = \"attendance/exceptions/edit_exception.html\"\n")
        new_lines.append("    form_class = EditExceptionForm\n")
        new_lines.append("    model = Exception\n")
        new_lines.append("    success_url = reverse_lazy(\"Attendance:exception\")\n\n")
        new_lines.append("    def form_valid(self, form):\n")
        new_lines.append("        response = super().form_valid(form)\n")
        new_lines.append("        SystemLog.objects.create(\n")
        new_lines.append("            user=self.request.user,\n")
        new_lines.append("            action=\"تعديل استثناء\",\n")
        new_lines.append("            description=f\"تم تعديل استثناء الموظف: {self.object.employee.name}\",\n")
        new_lines.append("            ip_address=self.request.META.get('REMOTE_ADDR')\n")
        new_lines.append("        )\n")
        new_lines.append("        return response\n\n\n")

        skip_until = 982 # AddPermission
        continue

    new_lines.append(line)

with open('/Users/zakaria/projects/antigravity/attendance/Attendance/views.py', 'w') as f:
    f.writelines(new_lines)
