"""
Django settings for HTI project.

Generated by 'django-admin startproject' using Django 3.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
from django.urls import reverse_lazy

# BASE_DIR adjusted for PyInstaller
if getattr(sys, 'frozen', False):
    BASE_DIR = Path(sys._MEIPASS)
else:
    BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

import environ

env = environ.Env(
    DEBUG=(bool, False)
)
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1', '::1', '127.0.0.1'])

CORS_ORIGIN_ALLOW_ALL = env.bool('CORS_ORIGIN_ALLOW_ALL', default=False)


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'VIPAlert',
    'Attendance',
    'rest_framework',
    'django_filters',
    'widget_tweaks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'VIPAlert.middleware.LoginRequiredMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'HTI.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'HTI.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# Check if we're using PostgreSQL (production)
db_engine = env('DB_ENGINE', default='')
if db_engine == 'django.db.backends.postgresql_psycopg2':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': env('DB_NAME', default='hti_vip'),
            'USER': env('DB_USER', default='hti'),
            'PASSWORD': env('DB_PASSWORD', default='Ht!V!p2021'),
            'HOST': env('DB_HOST', default='localhost'),
            'PORT': env('DB_PORT', default='5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            # user -> hti
            # password -> Ht!V!p2021
            # db -> hti_vip
            'ENGINE': 'django.db.backends.sqlite3',
            # Persistent DB path for desktop mode
            'NAME': os.path.join(os.path.dirname(sys.executable), 'db.sqlite3') if (getattr(sys, 'frozen', False) and os.environ.get('DESKTOP_MODE') == '1') else os.path.join(BASE_DIR, 'db.sqlite3'),
            # 'ENGINE': 'django.db.backends.postgresql_psycopg2',
            # 'NAME': 'hti_vip',
            # 'USER': 'hti',
            # 'PASSWORD': 'Ht!V!p2021',
        }

        # Host:
        #   ec2-54-87-179-4.compute-1.amazonaws.com
        # Database:
        #   ddasq51a6v73ee
        # User:
        #   owvprgwytrqjiu
        # Port:
        #   5432
        # Password:
        #   d5d928870ca5c6cf5b688acd242f28b67593c159c450d177bb21a8cc7062c3de
        # URI:
        #   postgres://owvprgwytrqjiu:d5d928870ca5c6cf5b688acd242f28b67593c159c450d177bb21a8cc7062c3de@ec2-54-87-179-4.compute-1.amazonaws.com:5432/ddasq51a6v73ee
        # Heroku CLI:
        #   heroku pg:psql postgresql-rigid-80888 --app htisystem
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'ar'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Africa/Cairo'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Celery Configuration (Disabled for Windows Desktop Mode)
if os.environ.get('DESKTOP_MODE') != '1':
    CELERY_BROKER_URL = env('CELERY_BROKER_URL', default='redis://localhost:6379/0')
    CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND', default='redis://localhost:6379/1')
    CELERY_ACCEPT_CONTENT = ['application/json']
    CELERY_TASK_SERIALIZER = 'json'
    CELERY_RESULT_SERIALIZER = 'json'
    CELERY_TIMEZONE = 'Africa/Cairo'
else:
    CELERY_BROKER_URL = None

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static"), ]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Media files (uploaded content)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')



# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = "VIPAlert.User"

LOGIN_URL = reverse_lazy("VIP:login")
LOGIN_REDIRECT_URL = reverse_lazy("Attendance:list")
LOGOUT_REDIRECT_URL = reverse_lazy("VIP:login")



CONTRACTS_ROOT = os.path.join(BASE_DIR, 'contracts')

PROTECTED_ADMIN_EMAIL = env('PROTECTED_ADMIN_EMAIL', default='admin@system.local')

REST_FRAMEWORK = {
    # Default to requiring authentication for all API endpoints
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated'
    ],
    'DATETIME_FORMAT': "%Y-%m-%d - %H:%M:%S", 
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend']
}
REST_SESSION_LOGIN = False

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'django_error.log'),
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}

# Cache configuration (required for rate limiting)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'attendance-cache',
    }
}
