# Generated by Django 3.2.4 on 2023-02-01 08:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[(0, 'Saturday'), (1, 'Sunday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=4096)),
                ('phone', models.CharField(blank=True, default='', max_length=4096)),
                ('attendance_id', models.CharField(max_length=256)),
                ('active', models.BooleanField(default=False)),
                ('current_vacations', models.FloatField(default=0, verbose_name='Current vacations')),
            ],
            options={
                'permissions': [('can_view_employees', 'View employees'), ('can_view_employee_records', 'View employee records'), ('can_create_employees', 'Add employees'), ('can_delete_employees', 'Delete employees'), ('can_edit_employees', 'Edit employees'), ('can_edit_employees_records', 'Edit employees records'), ('can_edit_export_report', 'Edit employees records')],
            },
        ),
        migrations.CreateModel(
            name='ExceptionType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='VacationType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ZKTDevice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=4096)),
                ('port', models.IntegerField(default=4370)),
                ('name', models.CharField(blank=True, default='', max_length=4096)),
                ('out_during_work', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None, null=True)),
                ('device', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Attendance.zktdevice')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Attendance.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None, null=True)),
                ('to_date', models.DateField(default=None, null=True)),
                ('note', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Attendance.employee')),
                ('vacation_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Attendance.vacationtype')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=4096)),
                ('timestamp', models.DateTimeField(default=None, null=True)),
                ('status', models.CharField(max_length=256)),
                ('punch', models.CharField(max_length=256)),
                ('uid', models.CharField(blank=True, default='', max_length=1024)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Attendance.zktdevice')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=4096)),
                ('start_time', models.TimeField(default=None, null=True)),
                ('end_time', models.TimeField(default=None, null=True)),
                ('allowed_start_time', models.TimeField(default=None, null=True)),
                ('calculate_start_time', models.TimeField(default=None, null=True)),
                ('allowed_end_time', models.TimeField(default=None, null=True)),
                ('calculate_end_time', models.TimeField(default=None, null=True)),
                ('next_day', models.BooleanField(default=False)),
                ('extra', models.BooleanField(default=False)),
                ('hourly', models.BooleanField(default=False)),
                ('auto_open', models.BooleanField(default=False)),
                ('auto_close', models.BooleanField(default=False)),
                ('shift_start_time', models.TimeField(default=None, null=True)),
                ('shift_end_time', models.TimeField(default=None, null=True)),
                ('shift_end_next_day', models.BooleanField(default=False)),
                ('by_finger_print_count', models.BooleanField(default=True)),
                ('days', models.ManyToManyField(to='Attendance.Day')),
            ],
            options={
                'permissions': [('can_view_profiles', 'View Profiles'), ('can_create_profiles', 'Add profile'), ('can_delete_profiles', 'Delete profiles'), ('can_edit_profiles', 'Edit profiles')],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Attendance.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=datetime.datetime(2023, 2, 1, 8, 2, 26, 235757, tzinfo=utc))),
                ('end', models.DateTimeField(default=datetime.datetime(2023, 2, 1, 8, 2, 26, 235757, tzinfo=utc), null=True)),
                ('note', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Attendance.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Exception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None, null=True)),
                ('note', models.TextField()),
                ('type', models.CharField(choices=[('early_exit', 'Early exit'), ('late', 'Late')], default=None, max_length=50, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Attendance.employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='default_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Attendance.profile'),
        ),
        migrations.AddField(
            model_name='employee',
            name='device',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Attendance.zktdevice'),
        ),
    ]
