# Generated by Django 3.2.4 on 2023-02-01 10:23

import datetime
from django.db import migrations, models
import datetime as dt
utc = dt.timezone.utc


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrawork',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 1, 10, 23, 1, 343850, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='extrawork',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 1, 10, 23, 1, 343850, tzinfo=utc)),
        ),
    ]
