# Generated by Django 3.2.4 on 2023-02-06 10:55

import datetime
from django.db import migrations, models
import datetime as dt
utc = dt.timezone.utc


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0002_auto_20230201_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrawork',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 6, 10, 55, 24, 285504, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='extrawork',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 6, 10, 55, 24, 285504, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.CharField(choices=[('early_exit', 'Early exit'), ('late', 'Late'), ('attendance', 'Attendance')], default='attendance', max_length=50, null=True),
        ),
    ]
