# Generated by Django 3.2.4 on 2023-02-07 13:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0003_auto_20230206_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='note',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='extrawork',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 7, 13, 51, 13, 381549, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='extrawork',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 7, 13, 51, 13, 381549, tzinfo=utc)),
        ),
    ]
