# Generated by Django 3.2.4 on 2023-02-13 07:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0004_auto_20230207_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrawork',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 13, 7, 57, 59, 64455, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='extrawork',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 13, 7, 57, 59, 64455, tzinfo=utc)),
        ),
    ]
