# Generated by Django 3.2.4 on 2023-03-26 11:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0005_auto_20230213_0958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacation',
            old_name='vacation_type',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='exception',
            name='type',
            field=models.CharField(choices=[('early_exit', 'خروج مبكر'), ('late', 'تأخير')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='extrawork',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 26, 11, 12, 57, 280388, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='extrawork',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 26, 11, 12, 57, 280388, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.CharField(choices=[('early_exit', 'خروج مبكر'), ('late', 'تأخير')], default='attendance', max_length=50, null=True),
        ),
    ]
