# Generated by Django 3.2.4 on 2023-03-26 11:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0006_auto_20230326_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacation',
            old_name='type',
            new_name='vacation_type',
        ),
        migrations.AlterField(
            model_name='extrawork',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 26, 11, 15, 4, 548570, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='extrawork',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 26, 11, 15, 4, 548570, tzinfo=utc)),
        ),
    ]
