# Generated by Django 4.2.24 on 2026-02-22 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0007_auto_20230326_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrawork',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 22, 16, 4, 38, 213707, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='extrawork',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 22, 16, 4, 38, 213411, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='record',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='user_id',
            field=models.CharField(db_index=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name='workday',
            name='date',
            field=models.DateField(db_index=True, default=None, null=True),
        ),
    ]
