# Generated by Django 4.2.24 on 2026-02-23 20:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Attendance", "0008_alter_extrawork_end_alter_extrawork_start_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="day",
            name="day",
            field=models.CharField(
                choices=[
                    (0, "السبت"),
                    (1, "الأحد"),
                    (2, "الاثنين"),
                    (3, "الثلاثاء"),
                    (4, "الأربعاء"),
                    (5, "الخميس"),
                    (6, "الجمعة"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="extrawork",
            name="end",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 2, 23, 20, 53, 12, 102388, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="extrawork",
            name="start",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 2, 23, 20, 53, 12, 101466, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
