# Generated by Django 4.2.24 on 2026-02-23 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Attendance", "0009_alter_day_day_alter_extrawork_end_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extrawork",
            name="end",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 2, 23, 20, 54, 45, 637173, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="extrawork",
            name="start",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 2, 23, 20, 54, 45, 636515, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
