# Generated by Django 4.2.24 on 2026-03-29 12:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("Attendance", "0010_alter_extrawork_end_alter_extrawork_start"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extrawork",
            name="end",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name="extrawork",
            name="start",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
