# Generated by Django 4.2.24 on 2026-04-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Attendance", "0011_alter_extrawork_end_alter_extrawork_start"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="record",
            name="status",
            field=models.CharField(
                choices=[
                    ("early_exit", "خروج مبكر"),
                    ("late", "تأخير"),
                    ("attendance", "حضور"),
                ],
                default="attendance",
                max_length=50,
                null=True,
            ),
        ),
    ]
