# Generated by Django 4.2.24 on 2026-05-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Attendance", "0012_alter_record_note_alter_record_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={
                "ordering": ("id",),
                "permissions": [
                    ("can_view_employees", "View employees"),
                    ("can_view_employee_records", "View employee records"),
                    ("can_create_employees", "Add employees"),
                    ("can_delete_employees", "Delete employees"),
                    ("can_edit_employees", "Edit employees"),
                    ("can_edit_employees_records", "Edit employees records"),
                    ("can_edit_export_report", "Edit employees records"),
                ],
            },
        ),
        migrations.AddField(
            model_name="profile",
            name="late_threshold",
            field=models.IntegerField(
                default=15,
                help_text="Number of minutes after start_time to consider the employee late.",
            ),
        ),
    ]
