# Generated by Django 4.2.24 on 2026-05-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Attendance", "0013_alter_employee_options_profile_late_threshold"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="full_month_work",
            field=models.BooleanField(
                default=False, help_text="If True, every day is a work day."
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="name",
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
    ]
