# Generated by Django 4.2.24 on 2026-05-06 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Attendance", "0014_profile_full_month_work_alter_employee_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="workday",
            name="late_seconds",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="workday",
            name="out_return_hours",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="workday",
            name="overwork_hours",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="workday",
            name="work_hours",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="extrawork",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extrawork_set",
                to="Attendance.employee",
            ),
        ),
        migrations.AlterField(
            model_name="holiday",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="holiday_set",
                to="Attendance.employee",
            ),
        ),
    ]
