# Generated by Django 4.2.24 on 2026-05-06 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Attendance", "0015_attendanceexception_workday_late_seconds_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="workday",
            index=models.Index(
                fields=["employee", "date"], name="Attendance__employe_1fa4e2_idx"
            ),
        ),
    ]
