# Generated by Django 4.2.30 on 2026-05-06 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Attendance", "0016_attendanceexception_remove_exception_employee_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceException",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=None, null=True)),
                ("note", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[("early_exit", "خروج مبكر"), ("late", "تأخير")],
                        default=None,
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "Attendance_exception",
            },
        ),
        migrations.AlterField(
            model_name="employee",
            name="attendance_id",
            field=models.CharField(db_index=True, max_length=256),
        ),
        migrations.DeleteModel(
            name="Exception",
        ),
        migrations.AddField(
            model_name="attendanceexception",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exception_set",
                to="Attendance.employee",
            ),
        ),
    ]
