# Generated by Django 4.2.24 on 2026-05-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Attendance",
            "0017_attendanceexception_alter_employee_attendance_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="workday",
            name="early_exit_seconds",
            field=models.IntegerField(default=0),
        ),
    ]
